### ISSUE TITLE
CUNIT3 keyword removed from header

### ISSUE THREAD

**Issue by PeterKamphuis** [SoFiA-Admin/SoFiA-2#11]
I ran SoFiA2 on a data cube that is lacking a CUNIT3 keyword but has units of m/s on the spectral axis. The run went smoothly but afterwards the output mask has a spectral axis which is converted to km/s.  However, since there is still no CUNIT3 some programs (kvis) assume the cube to be in m/s.

I realise the original error is with me using cubes without CUNITS but I do think the axis should either not be converted or SoFiA should throw an error or the CUNIT3 should be explicitly set to km/s.

**Comment by PeterKamphuis** [comment]
Even worse if I add the CUNIT3 keyword it is removed from the header while the conversion is still done.

**Comment by PeterKamphuis** [comment]
Actually I was doing the conversion of the axis somewhere myself without realizing. However, the CUNIT keyword is removed from the header.

**Comment by SoFiA-Admin** [comment]
Thanks for reporting this issue. Indeed, the `CUNITn` header entries were not copied across to any of the output products. I have fixed this, and they should now appear in any FITS files produced by SoFiA 2 (commit cc92ab7bf8695644afbd07c21d07cd880ee22519). Note that SoFiA 2 does not do any unit conversions, but always retains the data in its original form as supplied by the input data cube.
