### ISSUE TITLE
Separate nr of mask dilation iterations for XY and Z

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#13]
Could see SoFiA-1 as an example:

https://github.com/SoFiA-Admin/SoFiA/blob/3bf19e9b2b817bcdf55558049dd2355b0850162f/sofia/parametrisation.py#L58-L86

**Comment by SoFiA-Admin** [comment]
This has been implemented, and new parameters `dilation.iterationsXY` and `dilation.iterationsZ` are available to control the number of spatial and spectral iterations (see 700f73b0eb382b2a68f7df1e8071e619a55b3244).
