### ISSUE TITLE
XY mask dilation should tend to a circle

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#14]
See SoFiA-1 as an example:

https://github.com/SoFiA-Admin/SoFiA/blob/3bf19e9b2b817bcdf55558049dd2355b0850162f/sofia/parametrisation.py#L75

Note that dilation with progressively large XY structures always start from the original mask.

**Comment by SoFiA-Admin** [comment]
This has been implemented as requested (see 700f73b0eb382b2a68f7df1e8071e619a55b3244).
