### ISSUE TITLE
moment-1 and -2 images with positive voxels only

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#16]
Moment-1 and -2 images can have nonsensical/Nan values at X,Y positions where negative channels are included in the detection mask. It might therefore be useful to produce moment-1 and -2 images calculated using positive voxels only.

These "positive" moment-1 and -2 images should not replace the normal ones, but could be provided as additional products.

The SoFiA implementation could be used to guide the SoFiA-2 implementation of this. See https://github.com/SoFiA-Admin/SoFiA/commit/97e81979533744770869d8085c3a6e87a8c3512e .

Note that the moment-0 image used to normalise the "positive" moment-1 and -2 images should also be made using positive voxels only. However, I suggest not to write such "positive" moment-0 image to disc because of its bias towards positive flux.

**Comment by SoFiA-Admin** [comment]
Progress update: The moment calculation in SoFiA 2 has been changed as suggested by calculating moments 1 and 2 from only positive pixels, while moment 0 continues to be calculated from both positive and negative pixels. Currently, this replaces the old moment 1 and 2 calculation, and there is no option yet for choosing between the old and new method.

**Comment by SoFiA-Admin** [comment]
As discussed at our meeting, I have modified the code to allow users to explicitly specify the threshold that should be applied to moment 1 and 2 maps using the `output.thresholdMom12` option (see c32c73388f28ef3757c1fe00890e90924efaab0f). This option is set to 0 by default which therefore defaults to the threshold originally requested.

A few things to note:

* Any positive or negative numerical value can be used, e.g. a large negative value could be used to ensure that all channels are included in the moment map calculation.
* The value is **relative** to the **local RMS** value, hence `output.thresholdMom12 = 3.0` would apply a 3σ threshold.
* The threshold will only be applied to moment 1 and 2 maps of **individual detections**, but not to moment 0 maps or global moment 1 and 2 maps. A threshold of 0 will always be applied to global moment 1 and 2 maps, as the noise level is generally expected to vary quite substantially across the full field, so a generic absolute or relative value wouldn’t make much sense. Moment 0 maps will always use all data to avoid creating a positive flux bias.

I will close this issue now, but feel free to reopen if there are any issues with the current implementation.
