### ISSUE TITLE
Account for pixel and beam size in integrated SNR thresholding (reliability.fmin)

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#17]
The reliability module allows users to apply (besides the reliability threshold itself) an `integrated SNR` threshold to the catalogue of detections. The threshold is set by the parameter `reliability.fmin` and is applied to the quantity `F_sum / sqrt(N)`, where `F_sum` is the sum of all voxel values in the mask defining an object, and `N` is the number of voxels.

In fact, `F_sum / sqrt(N)` does not take into account that voxels are not independent and, therefore, it is not exactly the `integrated SNR`. This makes life difficult for users. Having to calculate every time what `integrated SNR` threshold corresponds to what `reliability.fmin` is frustrating. Also, this makes it difficult to run the `integrated SNR` threshold in a consistent way on a set of cubes with varying beam or pixel size.

The proposal here is to account for the pixel and beam size in this algorithm, and thus apply the threshold `reliability.fmin` to the quantity `integrated SNR = F_sum / sqrt(N * Beam_area)` in SoFiA-2.

**Comment by SoFiA-Admin** [comment]
This has been implemented as suggested. A new `reliability.minSNR` parameter with a default value of 3 is now available and replaces the old `fmin` parameter (see 9bbdbd27a5a41a6ed310432f7f807a2e7f3e1200). Note that this requires accurate beam information to be present in the header. If no beam information is found, then the beam solid angle is assumed to be one, so SoFiA will fall back to the old `fmin` mechanism in this case.
