### ISSUE TITLE
CROTA2 dropped from header leads to wrong HI overlays

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#19]
As pointed out  in  #10, it would  be good to copy more header keys of the input cube to the SoFiA FITS products.

Here I'm opening a separate issue for keys whose removal from the header leads to incorrect science -- hence tentatively flagging this as a bug (but change it as you see fit).

One such key is CROTA2. On large fields, ignoring rotation leads to artificial HI-optical offsets.

**Comment by SoFiA-Admin** [comment]
Thanks for flagging this issue. Indeed, my plan is to eventually copy all header elements from the input cube (as requested in #10) and then delete the ones that aren’t needed, such as 3rd axis parameters in a 2D moment map.

As an aside: note that the `CROTAn` keywords are deprecated by the FITS standard and should not be used. This might be the reason for why I never included them to begin with.

**Comment by SoFiA-Admin** [comment]
I have updated SoFiA 2, and `CROTAn` keywords are now copied across when a new data cube is being created (1803025a419df52447add5d9b3ea5eed53760089). This issue can now be closed. Please feel free to reopen if things don’t work as expected.

**Comment by paoloserra** [comment]
Thanks!
