### ISSUE TITLE
wcslib dependancy across modern machines

### ISSUE THREAD

**Issue by teuben** [SoFiA-Admin/SoFiA-2#20]
Perhaps nice to add would be examples of the package names across different linux/mac package managers. the current readme appears to be debian/ubuntu centric:

      ubuntu/debian:   apt install wcslib-dev
      redhat/centos:   yum install wcslib-devel
      macosx/brew:     brew install wcslib
      macosx/port:     port install wcslib  (not confirmed)

I also noted on my rogue mac, installing wcslib pulled in cfitsio. Didn't test that on other machines, as they already had those.

**Comment by SoFiA-Admin** [comment]
Thank you very much for compiling the `wcslib` package names for different operating systems and software repositories. As I am using Ubuntu, I have no knowledge of how the package is called in other repositories or whether they even provide `wcslib` at all, so it is most useful to have that information available and confirmed. I have updated the wiki and `README` file to add the different package names.

**Comment by SoFiA-Admin** [comment]
Thank you again for your input. With the `README` file updated, this issue can now be closed.
