### ISSUE TITLE
Link to an example file for regression?

### ISSUE THREAD

**Issue by teuben** [SoFiA-Admin/SoFiA-2#21]
It would be very useful (if not essential) if there is a simple example anybody could use to verify the code works, plus it could give a speed benchmark and some resulting number so the user know it works. Ideally this benchmark cube is under control of the sofia2 team. One option would be to provide a code to make a cube, because that test cube should not be stored in github. But a link to some (archive) site I guess is ok, especially if it's real data :-)

**Comment by SoFiA-Admin** [comment]
Thank you for the suggestion to provide a test data cube for verification. In fact, we do already provide such a cube on the SoFiA 1 wiki on GitHub, however I am now providing a copy on the SoFiA 2 wiki as well:

https://github.com/SoFiA-Admin/SoFiA-2/wiki/documents/sofia_test_datacube.tar.gz

The test data cube comes with a SoFiA parameter file and a folder containing reference output files that users can compare their output against.

**Comment by teuben** [comment]
thank you, i got now. I never knew about the wiki (lazy guy who just git
clone's). so perhaps a hint in the README about the wiki/benchmark?

**Comment by SoFiA-Admin** [comment]
Thank you for that suggestion, I added a sentence to the `README` file to make users aware of the test data cube on the wiki. I will close this issue as resolved now.
