### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by teuben** [SoFiA-Admin/SoFiA-2#22]
Using a Makefile would be more unix like prevents the repeated options I see in compile.sh
One option would be to make a variable with the options
cflags=--std=c99 --pedantic -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-unused-function -Wfatal-errors -O3
to at least avoid the "do not repeat yourself" principle, but with a Makefile you get the macro redefinition for free.

Plus you can then do
        make clean

**Comment by teuben** [comment]
it was snowing here, so I made an example Makefile, see  my pull request. hopefully you can use it.

**Comment by SoFiA-Admin** [comment]
Thank you very much for taking the time to create a Makefile for SoFiA 2. I tested it on my computer, and compilation appears to be working fine, so I have merged your pull request. I will also update the `README` file to mention that `make` can be used as an alternative for installing SoFiA.

**Comment by SoFiA-Admin** [comment]
With the `Makefile` being available, this issue can now be closed.
