### ISSUE TITLE
OMP_NUM_THREADS ignored

### ISSUE THREAD

**Issue by teuben** [SoFiA-Admin/SoFiA-2#25]
The default for pipeline.threads = 0 suggested to me that it would listen to OMP_NUM_THREADS, instead it was using the max. In fact, it's always ignoring OMP_NUM_THREADS and the only way to set threads is via a sofia par setting. I don't think this is an industry standard, and a bit unfriendly to those running a series of benchmarks and forcing them to keep changing the par file for this.    I suspect this is a small change in the code.

here's an interesting discussion:
https://stackoverflow.com/questions/22813923/difference-between-num-threads-vs-omp-set-num-threads-vs-omp-num-threads

I would find the most user friendly method where a setting of 0 will use OMP_NUM_THREADS or the max. and yes, when set to a non-zero value, this will override OMP_NUM_THREADS

**Comment by SoFiA-Admin** [comment]
Thank you for this suggestion for improvement, which is indeed an excellent idea. I have modified the way in which the number of threads is defined in exactly this way, with `pipeline.threads = 0` now defaulting to `OMP_NUM_THREADS`, while a value > 0 will explicitly set the specified number of threads (see ba7411cd7691d4b747c2e667a2a772521fbc6441 for the implementation details).
