### ISSUE TITLE
advanced command line usage ?

### ISSUE THREAD

**Issue by teuben** [SoFiA-Admin/SoFiA-2#26]
I know that you have to set everything via the sofia.par style file, but this forces advanced users to write parsers, whereas I would imagine allowing something like
      sofia  sofia.par input.data=M51.fits output.filename=M51
would allow one to inherit from a template and use existing infrastructure to loop over parameters a little easier.

I happen to have a parameter editor program that substitutes key=val entries , something like

      paredit sofia.par input.data=M51.fits output.filename=M51 > m51.par
      sofia m51.par

which is the other approach. But not everybody has this, and my proposed style could be useful for users. So consider is a wishlist item

**Comment by SoFiA-Admin** [comment]
Thank you for this suggestion. I agree that this would be a useful feature to have, so I implemented a much more flexible way of passing user settings to SoFiA (see f5cdfd2755a3356bfdcff7b62a6d253b5d332674).

SoFiA now accepts _any_ number of command-line arguments (as long as there is at least one). An argument can either be a parameter file name or a parameter setting of the form ‘key=value’. These can be given in any order, and any number of direct settings or files can be provided. Recurring parameters will get overwritten, with the last setting taking precedence over any previous ones.

As direct settings are identified by the presence of the ‘=’ character, file names are no longer allowed to contain that character. This minor disadvantage is outweighed by the additional flexibility.

Please test and let me know if you find any issues with the new version.
