### ISSUE TITLE
Create SNR maps

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA-2#28]
SoFiA 2 currently created number-of-channels maps which can be used to calculate the per-pixel signal-to-noise ratio of any flux value in the moment-0 map. It would be desirable to derive SNR maps straight away by taking the local RMS noise level and beam header information into account. This should be straightforward for individual sources where the noise can be assumed to be constant, but might be more challenging for the full field, as the noise might vary substantially. A possible solution might be to derive SNR maps from the noise-normalised cube rather than the original cube.

**Comment by SoFiA-Admin** [comment]
This has now been implemented (see b8000f0d8c4cf21ff46ab786a185c9e52c1cfdb1). SNR maps are only calculated for individual sources and will replace the old channel maps. The new file suffix is `_snr.fits`. Global moment maps will still be accompanied by the original number of channels map, as the noise may not be constant across the full data cube.

**Comment by paoloserra** [comment]
@SoFiA-Admin could you please confirm that the SNR maps are `snr = mom0 / local_rms / sqrt(nchan)` , where `nchan` is the number-of-channels map that we used to write to disc, and `local_rms` is calculated on the cubelet?

**Comment by SoFiA-Admin** [comment]
@paoloserra Indeed, that’s how they are derived.
https://github.com/SoFiA-Admin/SoFiA-2/blob/56b3d052ea3b504a8a12cbd73f7bd956145501c3/src/DataCube.c#L5422
In the expression
```C
value_flux / (rms * sqrt((double)value_chan))
```
`value_flux` is taken from the moment 0 map, `rms` is the the local noise level from the catalogue and `value_chan` is extracted from the number of channels map.
