### ISSUE TITLE
SoFiA 1 transition: Create PV diagram FITS file for each detection

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#30]
In SoFiA-1 this is done at

https://github.com/SoFiA-Admin/SoFiA/blob/ac84cb9adfa6a0c2ade739e3db2636fbdf096629/sofia/cubelets.py#L118-L157

**Comment by SoFiA-Admin** [comment]
PV diagrams have now been incorporated into SoFiA (see 2eb62297ac605ab0ff510df95292d851fa7cbd6d). They are generated for each source whenever cubelets are enabled and are created along a line through the flux-weighted centroid (`x` and `y`) of each source that is rotated according to the kinematic major axis position angle (`kin_pa`). Unlike in SoFiA 1, the implementation in SoFiA 2 carries out a bi-linear interpolation of the four nearest pixels to each of the points along the line. PV diagrams have the file suffix `_pv.fits`. Please test and let me know if you find any issues.

**Comment by paoloserra** [comment]
Thank you @SoFiA-Admin !

I think before closing this we should validate the new PVD implementation by comparing with PVDs made with, e.g., KPVSLICE and SoFiA-1. I will do that in the coming days.

**Comment by paoloserra** [comment]
As pointed out by @vdhulst , let's be careful that we test this with cubes with a fixed pixel size, i.e., not with `CELSCAL = 1/F`

**Comment by paoloserra** [comment]
Here some comparisons between PV diagrams made by SoFiA (left) and those made by KPVSLICE (right).

In the first case, for a poorly resolved sources, there are some differences, but I find it difficult to say whether they are significant.

In the second case, for a well resolved sources, there are definitely differences. I plan to investigate further whether these are due to an offset in the central RA,Dec of the PVD.

While doing this comparison, I found that it would be convenient to add the PVD central RA,Dec and PA in the PVD FITS header. I had to go back to the SoFiA table to find that.

<img width="1248" alt="Screenshot 2022-05-30 at 09 28 06" src="https://user-images.githubusercontent.com/6591265/170940281-3bae10bd-c95e-4c7f-97fd-0be147eca79c.png">

<img width="1360" alt="Screenshot 2022-05-30 at 09 57 19" src="https://user-images.githubusercontent.com/6591265/170945510-4364664e-6550-474d-bb18-8334326aeae9.png">

**Comment by paoloserra** [comment]
To elaborate further on the high-res case above, here's another set of plots showing that there is an inconsistency between SoFiA and KPVSLICE offset axes judging from the position of the tickmarks (the SoFiA PVD is on the left).

However, KPVSLICE is clearly having some issues with this cube. E.g., in the middle panel you can see that the green circle visible along the supposedly zero-offset vertical line is stated to have offset = 0.6 arcmin.

<img width="1438" alt="Screenshot 2022-05-30 at 10 40 30" src="https://user-images.githubusercontent.com/6591265/170953296-b9754f09-d00d-4fad-910e-1c5b9c3dfa2c.png">
 
One possible problem is that this cube has some WCS rotation. The header is:

<img width="428" alt="Screenshot 2022-05-30 at 10 42 59" src="https://user-images.githubusercontent.com/6591265/170953732-33ea7d4d-ed71-4f4a-a961-df1d719eb84b.png">

So let me try this again but with a no-rotation cube to understand what's going on.

**Comment by paoloserra** [comment]
I've discovered that the zero-offset KPVSLICE issue reported in the previous post (i.e., the inconsistency between the displayed position axis tick marks and the reported offset value) appears also in a cube with no rotation.

I've discovered that this issue/bug manifests itself when the position axis of the PVD is longer than the side of the cube. See example below for a cube with no rotation indeed.

<img width="1045" alt="Screenshot 2022-05-30 at 12 26 46" src="https://user-images.githubusercontent.com/6591265/170973307-5a282501-3ca8-4a43-8df0-ddcd053149de.png">

And then another PVD from the same cube, same RA,Dec, same PA, with a shorter axis. Now the zero is at the right position.

<img width="1047" alt="Screenshot 2022-05-30 at 12 35 08" src="https://user-images.githubusercontent.com/6591265/170974853-1aaba953-9e5f-4fc1-b458-18993aaacf76.png">

So KPVSLICE should definitely not be used as a comparison for SoFiA-2 when the position axis of the PVD is very long!!

**Comment by paoloserra** [comment]
And here is some reassuring news. This is now for a cube with no rotation (but maybe rotation was not the problem anyway -- see previous post).

Left = SoFiA-2 PVD
Middle = KPVSLICE along an axis shown in the right panel.

Comparing the source name in the left panel with the PVD centre listed in the right panel you can see that RA,Dec are essentially the same. As for the PA, I've used the value listed in the SoFiA ASCII catalogue.

The two PVDs are consistent with one another. I don't see any significant differences.

<img width="1437" alt="Screenshot 2022-05-30 at 12 37 54" src="https://user-images.githubusercontent.com/6591265/170975254-2eda1a0d-6b8a-4330-9840-76141ab6f4cb.png">

Please comment on whether this is sufficient to close this issue.

**TBD: add RA,Dec,PA of the PVD to the PVD FITS header**

**Comment by SoFiA-Admin** [comment]
Thanks, @paoloserra, for checking the PV diagrams from SoFiA 2 against those from Karma. I am pleased to see that the almost perfect agreement between the two after discovering and working around the bug in kpvslice. From that point of view, I am satisfied that there are no substantial issues with SoFiA’s PV diagrams.

The only issue that remains is the discrepancy in the coordinate offsets between SoFiA 1 and 2. The attached plot shows the PV diagrams from SoFiA 1 (left) and 2 (right) for one of the galaxies in the test data cube. To create those, I ran SoFiA 2 on the test data cube and then fed the cube and SoFiA 2 output mask into SoFiA 1 for parameterisation to ensure that we use exactly the same mask in both cases.

![sofia-1_sofia-2_pv_comparison](https://user-images.githubusercontent.com/6572706/171074196-c906b2aa-1e32-4ee3-a6cb-af1eaafddd64.png)

As you can see, the PV diagrams look identical, but there is an offset of 1 pixel on the x-axis. This offset appears to be present for all three galaxies in the test data cube and suggests that we have an “off-by-one” error in either SoFiA 1 or SoFiA 2.

Regarding the centre and PA information in the FITS header, did you have any specific header keywords in mind for this, or is it fine to just add a comment?

**Comment by paoloserra** [comment]
> Regarding the centre and PA information in the FITS header, did you have any specific header keywords in mind for this, or is it fine to just add a comment?

I'm not aware of any standard keyword for this. Maybe we could use something like `pvd_x`, `pvd_y`, `pvd_pa`? Where `x` and `y` could be replaced with the values of `ctype1` and `ctype2`, respectively.

**Comment by SoFiA-Admin** [comment]
I ran SoFiA 1 and 2 on a noise-free test data cube containing a symmetric mock galaxy to compare the resulting PV diagrams. The following plots shows 3 PV diagrams from kpvslice (created by hand), SoFiA 2 and SoFiA 1 (from left to right):

![PV_comparison](https://user-images.githubusercontent.com/6572706/208356009-4844eed7-dbdd-40ef-a817-b938466fc7c1.png)

The good news is that the PVD from SoFiA 2 (centre) is spot-on, and both the angular offset and velocity axes are precisely centred on the mock galaxy, which is good to see and means that the PVDs coming out of SoFiA 2 can be trusted.

The PVD from kpvslice looks very similar and also appears to be correctly centred along the spatial axis. Minor differences between the two plots can presumably be explained by the fact that kpvslice does not appear to interpolate, but uses nearest-neighbour interpolation. In addition, the velocity axis is of course not centred, as the slit needs to be positioned by hand and is difficult to centre in velocity.

Lastly, the PVD from SoFiA 1 (coming from an independent source finding run with SoFiA 1) does not closely resemble any of the other PVDs and would not appear to be spatially centred either. While it is not entirely obvious why that is the case, it is clear that the PVDs produced by SoFiA 1 have several issues and should not be trusted.

Hence, I have reason to believe that the PVDs produced by SoFiA 2 are correct and accurate, while the spatial offset seen in earlier test are likely due to errors in the SoFiA 1 algorithm.
