### ISSUE TITLE
Ignoring x_min in the region settings

### ISSUE THREAD

**Issue by vlad7235** [SoFiA-Admin/SoFiA-2#43]
When I set a region in the parameter file, e.g. 
`input.region=[480,639,480,639,0,6667]`
the first value is ignored and the region uses x_min=0 instead of 480 in this example,
```
  Opening FITS file 'sky_dev.fits'.
  Reading FITS data with the following specifications:
    Data type:    -32
    No. of axes:  3
    Axis sizes:   643, 643, 6668
    Region:       0-639, 480-639, 0-6667
    Memory used:  2604.7 MB
  Progress:  |==================================================| 100%

```
Likely the problem is in the **Array_siz_get** method which returns zero for the first element of **Array_siz** object.

**Comment by vlad7235** [comment]
SOLVED: it is not Python list, the string should be without [ ].
 input.region=480,639,480,639,0,6667

**Comment by SoFiA-Admin** [comment]
Thank you for reporting this issue. Indeed, SoFiA 2 expects the region to be just a plain, comma-separated list of six integer values. As the string `[480` does not represent a valid integer number, it will be replaced with zero instead.
