### ISSUE TITLE
Plotting tools for SoFiA output

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA-2#48]
The purpose of this issue is to collect ideas for developing plotting modules that can be used to visualise output data created by SoFiA. The following things could be plotted:

* Moment maps
* Integrated spectrum
* Contours on top of optical/multi-wavelength data
* PV diagrams
* ...

Such a plotting tool would ideally be implemented in Python independently of the actual SoFiA 2 code and operate directly on the FITS files and spectra produced by SoFiA.

**Comment by paoloserra** [comment]
https://github.com/kmhess/SoFiA-image-pipeline

**Comment by SoFiA-Admin** [comment]
Any follow-on discussion should occur in the SoFiA-image-pipeline GitHub repository. This issue can now be closed.
