### ISSUE TITLE
add linker.positivity option to only merge positive pixels

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#5]
This dangerous SoFiA-1 feature is very useful when using SoFiA to make clean masks. It would be good to include it in SoFiA-2

**Comment by SoFiA-Admin** [comment]
This option has now been implemented (see 972d5cc4e45e278b83ac537c7ff934ad6271323b). If `linker.positivity = true`, then all negative pixels will be discarded and only pixels with flux density ≥&nbsp;0 will be linked. Note that this requires the reliability module to be disabled. Please test and let me know if there are any issues with the new feature. I will close this issue now, but please feel free to reopen if necessary.
