### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by LKHZ** [SoFiA-Admin/SoFiA-2#52]
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Stack.c
: no file or dicteryc/SoFiA-2/src/Stack.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Path.c
: no file or dicteryc/SoFiA-2/src/Path.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Array_dbl.c
: no file or dicteryc/SoFiA-2/src/Array_dbl.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Array_siz.c
: no file or dicteryc/SoFiA-2/src/Array_siz.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Map.c
: 没有那个文件或目录c/SoFiA-2/src/Map.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Matrix.c
: no file or dicteryc/SoFiA-2/src/Matrix.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/LinkerPar.c
: no file or dictery
  Compiling src/Parameter.c
: no file or dicteryc/SoFiA-2/src/Parameter.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Source.c
: no file or dicteryc/SoFiA-2/src/Source.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Catalog.c
: no file or dicteryc/SoFiA-2/src/Catalog.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/Flagger.c
: no file or dicteryc/SoFiA-2/src/Flagger.c
gcc: fatal error: no input files
compilation terminated.
  Compiling src/WCS.c
: no file or dicteryc/SoFiA-2/src/WCS.c

**Comment by SoFiA-Admin** [comment]
Thank you for reporting this issue. Without additional information on what exactly you have been trying to do, I will not be able to diagnose the problem. The error messages as such would appear to make little sense and should not occur if you simply download and extract the SoFiA repository and then run the `compile.sh` script in that directory from the command line, as specified in the installation instructions. Can you briefly describe the steps that you have carried out and that resulted in those error messages?

**Comment by LKHZ** [comment]
Thank you for your letter.



I cloned your repository on github, installed GCC,g++,wcslib, and ran the compile. sh file .



I don't understand why this mistake occurs, please take a look at the cause.





I'm looking forward to hearing from you
        
    LichunSun
| |
孙利春
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/1/2021 ***@***.***> wrote：

Thank you for reporting this issue. Without additional information on what exactly you have been trying to do, I will not be able to diagnose the problem. The error messages as such would appear to make little sense and should not occur if you simply download and extract the SoFiA repository and then run the compile.sh script in that directory from the command line, as specified in the installation instructions. Can you briefly describe the steps that you have carried out and that resulted in those error messages?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SoFiA-Admin** [comment]
Thank you for providing those details. From what I can see, the problem seems to be that the compiler cannot find the source files. For example, the compiler is looking for `Stack.c` to compile it, but it doesn’t find that file. What I don’t understand is why the error message states that the file `dicteryc/SoFiA-2/src/Stack.c` wasn’t found, because the `compile.sh` script explicitly looks for `src/Stack.c`: https://github.com/SoFiA-Admin/SoFiA-2/blob/8cbdf6ef64aabc10f50bdefca7b7d760f127a5f2/compile.sh#L57 and not `dicteryc/SoFiA-2/src/Stack.c`, so the error message would not appear to make any sense. Out of curiosity, which operating system are you actually using? Is there actually a directory named `dicteryc/SoFiA-2/src/`? If yes, does it contain the source files such as `Stack.c`?

**Comment by LKHZ** [comment]
Thank you for your letter.



I use Ubuntu18.04 system.



Let me show you the files contained under my folder. I wonder if I made a mistake in setting the path？







Looking forward to hearing from you.



    LichunSun
| |
孙利春
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/1/2021 ***@***.***> wrote：

Thank you for providing those details. From what I can see, the problem seems to be that the compiler cannot find the source files. For example, the compiler is looking for Stack.c to compile it, but it doesn’t find that file. What I don’t understand is why the error message states that the file dicteryc/SoFiA-2/src/Stack.c wasn’t found, because the compile.sh script explicitly looks for src/Stack.c: https://github.com/SoFiA-Admin/SoFiA-2/blob/8cbdf6ef64aabc10f50bdefca7b7d760f127a5f2/compile.sh#L57 and not dicteryc/SoFiA-2/src/Stack.c, so the error message would not appear to make any sense. Out of curiosity, which operating system are you actually using? Is there actually a directory named dicteryc/SoFiA-2/src/? If yes, does it contain the source files such as Stack.c?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SoFiA-Admin** [comment]
Thank you. I use Ubuntu myself, so I am pretty confident that the installation under Ubuntu should work out of the box. Try the following steps:

1. Ensure that the packages `gcc` and `wcslib-dev` and all of their dependencies are installed through your package manager. (There is not need to install `g++`, as SoFiA is written entirely in C.)
2. Download the SoFiA repository from GitHub and extract it into a directory of your choice.
3. Enter the SoFiA directory and run `./compile.sh -fopenmp`.

This is the standard installation procedure and should work without any issues. There is no need to set any paths or environment variables, as SoFiA doesn’t require those. Let me know if you can get the installation to work following the step-by-step instructions above.

**Comment by LKHZ** [comment]
Thank you for your letter

I found out that I didn't have permission to open the coplile.sh file

I executed the following command and it was ready to install normally

    chmod 777 compile.sh




In a word, thank you very much for your help before, and we look forward to further communication in the future.





    LichunSun



| |
孙利春
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/2/2021 ***@***.***> wrote：

Thank you. I use Ubuntu myself, so I am pretty confident that the installation under Ubuntu should work out of the box. Try the following steps:

Ensure that the packages gcc and wcslib-dev and all of their dependencies are installed through your package manager. (There is not need to install g++, as SoFiA is written entirely in C.)
Download the SoFiA repository from GitHub and extract it into a directory of your choice.
Enter the SoFiA directory and run ./compile.sh -fopenmp.

This is the standard installation procedure and should work without any issues. There is no need to set any paths or environment variables, as SoFiA doesn’t require those. Let me know if you can get the installation to work following the step-by-step instructions above.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SoFiA-Admin** [comment]
I am pleased to hear that you have managed to get SoFiA installed in the end. I will close this issue now, but please feel free to open a new issue if you run into any other issues.

**Comment by LKHZ** [comment]
Ok,Thank you.


| |
孙利春
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/3/2021 ***@***.***> wrote：

I am pleased to hear that you have managed to get SoFiA installed in the end. I will close this issue now, but please feel free to open a new issue if you run into any other issues.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
