### ISSUE TITLE
Improvements to reliability auto-kernel

### ISSUE THREAD

**Issue by SoFiA-Admin** [SoFiA-Admin/SoFiA-2#55]
As discussed, a few improvement to the basic implementation of the reliability auto-kernel feature would be worthwhile and will be captured in this new issue. Most notably, we would want the user to be able to set some of the currently hard-coded parameters controlling the algorithm, in particular:

* Maximum number of iterations (currently hard-coded to 30)
* Threshold of the median for convergence (currently hard-coded to 0.05)

Other parameters that could be made adjustable include the step size in each iteration and the default kernel size if the algorithm fails to converge. Additional suggestions are welcome.

**Comment by paoloserra** [comment]
@SoFiA-Admin I think this was fixed by https://github.com/SoFiA-Admin/SoFiA-2/commit/8a227510e8e766ec879ea4466e1e04ddf180d8f7 and can be closed.
