### ISSUE TITLE
Understanding how the ripple filter works

### ISSUE THREAD

**Issue by kmhess** [SoFiA-Admin/SoFiA-2#58]
Original questions were: if (a) the noise cube is written after both the noise scaling and a ripple filter is applied or before the ripple filter is applied. (b) what does the ripple filter do at the edges? (For example, I was having trouble getting rid of baselines that would turn up at the edge of the cube which I was hoping the ripple filter would deal with, but I couldn't inspect the output from the ripple filter, so am not really sure what was going on).

Solution exists: the filtered cube is generated after the ripple filter and can be used to inspect the output. (filtered cube is what is passed to S+C finder)

Proposed solution: 
* Include in the user manual a description of how the results of the ripple filter can be inspected.

Not discussed (on 17/1/21): what the ripple filter does at the edges.  Also doesn't seem to be in the user manual.

**Comment by SoFiA-Admin** [comment]
Thanks, @kmhess, for that suggestion. I updated the user manual to point out how the effect of the ripple filter can be assessed.

Regarding the edges, I don’t fully understand the nature of the issue. The ripple filter simply measures the median within a 3D running window of user-defined size and then subtracts that median from the data. Whether a pixel is near the spatial or spectral edge or not does not really matter.

The only thing to be aware of is that the ripple feature must be sufficiently extended for the filter to be effective. A high-frequency ripple or narrow artefact cannot be removed, as this would require selecting a very small spatial and/or spectral window size which would have the potential to subtract genuine astronomical signal as well.

Hence, the filter will only be effective for ripples that are significantly more extended (both spatially and spectrally) than the astronomical sources in the data cube and will therefore work best on extragalactic HI cubes.

**Comment by SoFiA-Admin** [comment]
As discussed on Monday, this issue can now be closed.
