### ISSUE TITLE
channels recorded in spec.txt, cat.txt, noise.txt

### ISSUE THREAD

**Issue by kmhess** [SoFiA-Admin/SoFiA-2#66]
If the user asks SoFiA-2 to only run over a limited number of channels (the last two values in input.region), then the channels that are output in the spec.txt, noise.txt, and the x,y,z, and their min's and max's in cat.txt are relative to *those* values, and don't represent the channels in the original cube.

I propose that the channels and the ra/dec pixels written should be relative to the original cube, regardless of the subregion the user selects because there is no other record in the text files of the users's "new" reference pixel.

**Comment by kmhess** [comment]
I think we decided this was "fixed" with `parameter.offset = True`, right?  I've included those instructions in the SoFiA Image Pipeline readme.

**Comment by kmhess** [comment]
When OptiFind is used, the z_max and z_min reported in the optifind_N_cat.txt (N=source id) are relative to the original cube rather than to the cubelet in which the source was found.  However, the channels reported in *_spec.txt for a source are relative to the cubelet.  This is true regardless of how parameters.offset is set.  I can understand where, in the *merged* catalog, this would be the desired behavior, but I think for the z_max and z_min in the unmerged catalogs, it should be relative to the cubelet so that spec.txt and the catalogs are consistent?

**Comment by SoFiA-Admin** [comment]
Thanks, I checked the source code, and indeed the channel numbers in the first column of the spectrum were always specified relative to the region. I have updated the code to make the spectral channel numbers adhere to the `parameter.offset` setting as well, like the source catalogue. This will make the behaviour consistent with the rest of SoFiA, and the user now controls whether the channels should be relative to the region (`parameter.offset = false`) or the full data cube (`parameter.offset = true`).

**Comment by panstarrs** [comment]
Hi This is a bit weird. I just tried this but it seems the results have not changed (i.e. the spectral channel numbers are alway relative to the region regardless of parameter.offset = false or true). Below are the steps that I took, and I'm not sure what I'm missing here.

1) cd SoFiA-2
2) git pull
3) ./compile.sh -fopenmp
4) cd */OptiFind
5) ./optifind.py <par_file> <source_list> <r_spat> <r_spec>
6) cat *cubelets/*_spec.txt

**Comment by SoFiA-Admin** [comment]
Hm, that’s not what I see when I specify a region in SoFiA. With `parameter.offset = false` the channels are relative to the region, while with `parameter.offset = true` they are relative to the full data cube. Are you sure that the command `sofia` on your computer points to the latest SoFiA installation? You can type “`which sofia`” to find out. If not, then try specifying the full path to the SoFiA executable,
```
./optifind.py <par_file> <source_list> <r_spat> <r_spec> <path_to_sofia_exe>
```
where the last parameter specifies the path to the correct version.

**Comment by SoFiA-Admin** [comment]
I just checked the source code of OptiFind again and discovered that OptiFind explicitly sets `parameter.offset = true` in line 208 of `optifind.py`. So the output from OptiFind should always be relative to the full cube (which indeed makes sense) irrespective of the `parameter.offset` setting in the template parameter file. Hence, changing `parameter.offset` will have no effect, but the channels should always be relative to the full cube rather than the region (at least with the latest development version of SoFiA).
