### ISSUE TITLE
moment image does not account for CELLSCAL='1/F'

### ISSUE THREAD

**Issue by vdhulst** [SoFiA-Admin/SoFiA-2#67]
Running the new sofia-imaging pipeline (https://github.com/kmhess/SoFiA-image-pipeline) I came across position errors for galaxies at the edge of the field in data on Fornax. The figure below compares an HI overlay of ESO 358-G063 (pipeline left, published figure in Loni+2021 right) and shows that the pipeline HI position is off.

<img width="762" alt="SoFiA-pipeline_vs_Loni+2021" src="https://user-images.githubusercontent.com/7922633/156331743-5fc10e39-b31a-4c85-b542-0a842f0adbf2.png">

I reproduced the moment image and cubelets with SoFiA-1 and found that apparently SoFiA-2 does not account for the appropriate scaling introduced by MIRIAD and indicated by the presence of the FITS keyword CELLSCAL = '1/F'

The mom0 image from SoFiA-1 is:

<img width="523" alt="fornax_source_sofia-1" src="https://user-images.githubusercontent.com/7922633/156332266-df788755-1c9f-488b-9919-25663a8842cd.png">

The mom0 image from SoFiA-2 is:

<img width="523" alt="fornax_source_sofia-2" src="https://user-images.githubusercontent.com/7922633/156332366-12a542d9-4b79-47f4-8c71-45d70c852d9b.png">

The SoFiA-1 mom0 image has the galaxy at the right (optical) position: 03h46m19.01s, -34d56m36.8s or 56.579208, -34.943556.

**Comment by vdhulst** [comment]
In the corresponding sub cubes the coordinates appear to be correct, so the problem arises when the moment images are being determined.

**Comment by SoFiA-Admin** [comment]
Thank you for reporting this issue. Indeed, SoFiA 2 does not specifically support the `CELLSCAL` keyword, as it is not part of the FITS standard. Internally, WCS conversion is done using `wcslib`, so all position measurements should be correct under the assumption that `wcslib` supports `CELLSCAL`, which I believe is the case.

The problem with the moment maps (and all other 2D maps) is that the frequency axis is lost, and hence the `CELLSCAL = '1/F'` information cannot be applied any more. This will become problematic if the field of view or the fractional bandwidth are large, resulting in the coordinates in those 2D images being off by potentially several pixels.

If we wanted to explicitly support `CELLSCAL`, then I see two possible solutions:

1. We could consider retaining the frequency axis in all 2D maps. These would then have a single frequency channel that we could set to the central channel of the source. FITS image display software that supports `CELLSCAL` (e.g. `kvis`) would then be able to show the correct coordinate system again.
2. Alternatively, we could explicitly manipulate the spatial WCS information in the header to adjust the `CRVALn` and `CDELTn` keywords for the two spatial coordinates to match the central frequency channel of the source. This would alleviate the need to keep the frequency axis and the resulting images would have the correct coordinates displayed even in software that does not support `CELLSCAL`.

Regridding, as done in SoFiA 1, is presumably not particularly useful. Firstly, it is slow and could potentially introduce artefacts. Secondly, the fractional bandwidth across an individual source will almost certainly be negligible, meaning that any position errors would be significantly smaller than the size of a pixel and hence unnoticeable.

We can discuss and agree on a preferred solution at our next meeting on Monday. Both solutions should be straightforward to implement.

**Comment by paoloserra** [comment]
I agree with @vdhulst, those approximations would not work for the full field moment maps. Regridding might be the only way.

We could of course decide that SoFiA-2 does not support cubes with CELLSCAL=1/F, and suggest that people regrid their cubes before using SoFiA.

Those cubes must have been made with Miriad, and Miriad is able to do the necessary regridding with the `regrid` task using `options=noscale`. Normally, this has the effect of having a `nan` XY frame around the cube. The width of this frame would change with Z coordinate. I think SoFiA-2 would be able to handle that.

**Comment by vdhulst** [comment]
I regridded the Fornax cube in Miriad as suggested by @paoloserra and that works fine. SoFiA does accept the regridded cube and produces a proper overall mom0 image and cubelet moment images.

**Comment by SoFiA-Admin** [comment]
Global moment maps indeed would not work without regridding. On the other hand, they should not be used for anything other than visual inspection anyway, as there is no guarantee that different sources aren’t blended together in the global moment maps. So we could consider dealing with `CELLSCAL = 1/F` in individual source maps, which should be fairly straightforward, but not in global maps. Printing an extra warning message in this case would probably be a good idea, too.

The issue with regridding the input data cube is that the beam size would no longer be constant and hence physical parameter conversion (integrated fluxes) would no longer be correct. (I think this may have been the original motivation for having it switched off by default).

**Comment by paoloserra** [comment]
There are lots of applications where you do want to use the full-field moment images.

In my opinion it is a lot clearer if we decide not to support cubes with `CELLSCAL = 1/F`, and request that users regrid. I.e., SoFiA-2 refuses to run on a cube with `CELLSCAL = 1/F`.

Alternatively, we can add a parameter that users can set to True if they want to force SoFiA-2 to run, having been warned that some of the SoFiA-2 products will be wrong. The parameter could be called something like `I-know-everything-about-cellscal-and-I-still-want-to-run-sofia`.

**Comment by SoFiA-Admin** [comment]
As a starting point, I added a check for `CELLSCAL = '1/F'` when the data cube is read in. A big warning message will now be printed if the keyword is found (see 4e29073a640cdcd3d14fd4217a0a7b300afacab5).

**Comment by vdhulst** [comment]
Since these cubes are produced by Miriad, maybe also add to the warning that the problem can be fixed by running `regrid` with `options=noscale`.
