### ISSUE TITLE
Single object products from different sofia runs in same cubelets folder

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#72]
Changed settings may result in less sources in a new sofia run compared to an old run. If `output.filename` is the same, single-object products from the old run will still be present in the cubelets folder after the new run if  sourceID > nr detections of the new run. That folder will thus contain a mix of old and new detections. I think this is not good. Maybe we should erase the content of the cublets folder before putting the  new files there if `output.overwrite = True`

**Comment by paoloserra** [comment]
Following some discussion the consensus is that we could check whether `rm -rf` exists on the system running SoFiA. If it does we could delete the old `cubelets` folder. If it doesn't we could rename it.

**Comment by vdhulst** [comment]
I added a few lines of code to sofia.c which removes old cubelet files if the same base_name and cubelet directory is used and overwrite=True. See pull request #92 from branch pa_min

**Comment by SoFiA-Admin** [comment]
Following our previous discussion, I have implemented a relatively safe solution that generates exactly the same filenames as we use for writing cubelets and then removes those from the cubelet directory if they already exist. This happens just before writing the new files to ensure that we delete as late as possible. The new implementation is in the same spirit as that proposed by @vdhulst, but does not rely on system commands and instead uses POSIX file access functions to directly unlink existing files that adhere to a specific naming scheme.

See 4907b2f4e5864554d3eaa05fa3e59323041c27f5 for details. Please test and let me know if you encounter any problems.
