### ISSUE TITLE
six galaxies found in test data cube

### ISSUE THREAD

**Issue by panstarrs** [SoFiA-Admin/SoFiA-2#78]
Does anyone find six galaxies instead of three in the test data cube ? I'm a new sofia user and using the latest version (2.4.1) but the input parameter file is the same sofia.par from sofia_test_datacube.tar.gz, so I wonder if my output makes sense or something is wrong ? the catalog is attached, thanks
[sofia_test_output_cat.txt](https://github.com/SoFiA-Admin/SoFiA-2/files/8656055/sofia_test_output_cat.txt)
.

**Comment by SoFiA-Admin** [comment]
Thanks for reporting this issue. Your installation is presumably working fine, as I got six detections as well when I tested the parameter file coming with the test data cube earlier. The reason for the extra detections would appear to be that this parameter file is outdated and still contains the old `reliability.fmin` parameter which has been replaced with `reliability.minSNR` (see https://github.com/SoFiA-Admin/SoFiA-2/wiki/SoFiA-2-Control-Parameters). Hence, the SNR threshold applied by the reliability module is much smaller than it should be, which explains the additional detections, which are likely noise peaks.

I will update the parameter file over the next few days to ensure that it works as expected for the latest version 2.4.1 of SoFiA.

**Comment by SoFiA-Admin** [comment]
I have updated the SoFiA test data cube parameter file and reference output files on the wiki (https://github.com/SoFiA-Admin/SoFiA-2/wiki/documents/sofia_test_datacube.tar.gz) to work correctly with the latest version of SoFiA. This should now yield 3 detections again, as expected, when running SoFiA 2.4.1.

**Comment by panstarrs** [comment]
Thanks for sorting this out quickly. I'm now having three detections as expected.
