### ISSUE TITLE
When CASAMB=T, can we get SoFiA to estimate a common beam at the start?

### ISSUE THREAD

**Issue by spectram** [SoFiA-Admin/SoFiA-2#79]
**Background**
CASA often fails to estimate the common beam after cleaning. This results in a Beam table in the fits file and the header keyword: "CASAMBM = T /CASA multiple BEAMS table present". Further, the header will not have the beam parameters in them.

**Argument**
This presents the opportunity for users to find the common beam in just the channels with detected sources. This can either be implemented for different cubelets or for all channels with detections. I understand that the reliability estimation diagnostics plots also need the beam parameters to be present in the header.

[Python implementation for the complex optimization problem](https://radio-beam.readthedocs.io/en/latest/commonbeam.html)

**Comment by spectram** [comment]
Is it worthwhile to estimate (& suggest or implement as default) kernels for S+C based on beam parameters and cellsize? Perhaps even linker radius?

**Comment by spectram** [comment]
Yikes. Just found the related open issue: https://github.com/SoFiA-Admin/SoFiA-2/issues/71

**Comment by paoloserra** [comment]
Let's close this one and keep everything in one place (#71)

Maybe open a separate issue on your other point (default S+C kernels and linker radii) given that it applies also to cubes with a constant beam.
