### ISSUE TITLE
ellipse fittinf results..

### ISSUE THREAD

**Issue by abhisek176** [SoFiA-Admin/SoFiA-2#83]
The major axis and minor axis provided by the ellipse fit seem like semi-major and semi-minor axis. I am using SoFiA 2.4.1. Can someone please confirm this?

**Comment by abhisek176** [comment]
Just adding to my previous query: I see in https://arxiv.org/pdf/astro-ph/9409081.pdf that Eq.2 and Eq.3 give a and b which are semi-major and minor axis. Is there something I am missing?

**Comment by SoFiA-Admin** [comment]
Thank you for raising this issue. Unfortunately I cannot reproduce your findings. I just tested SoFiA on a model image containing a single elliptical Gaussian component of FWHM 20″ × 15″, which corresponds to a standard deviation, σ, of 8.5″ × 6.4″. SoFiA reports a major and minor axis size of 17.0″ × 12.7″, which is exactly 2σ, as stated in the SoFiA user manual. Hence, the information in the user manual would appear to be correct, and the major and minor axis sizes from the ellipse fit indeed correspond to twice the standard deviation. How did you arrive at the conclusion that they must correspond to the semi-major/minor axis size?

**Comment by SoFiA-Admin** [comment]
From the image it would appear that the ellipse is far too big. Did you use the major/minor axis size from SoFiA as the semi-major/minor axis by any chance? The major/minor axis size from SoFiA should be twice the standard deviation along the major/minor axis of the object and hence should be much smaller judging from the plot.

In any case, the test image and SoFiA parameter file that I used are attached below.
[test_image.fits.gz](https://github.com/SoFiA-Admin/SoFiA-2/files/8916090/test_image.fits.gz)
[sofia.txt](https://github.com/SoFiA-Admin/SoFiA-2/files/8916099/sofia.txt)

**Comment by abhisek176** [comment]
Thank you. Yes, I got confused with pixel<>size conversation. The SoFiA-generated parameters are indeed fine. :)
