### ISSUE TITLE
Sanity check questions

### ISSUE THREAD

**Issue by spectram** [SoFiA-Admin/SoFiA-2#94]
I wanted confirmation on some essential aspects related to the files in the cubelet directory. The documentation alludes to this and the answers can be inferred, although not explicitly stated. 

1) '*_snr.fits' (page 29) - Is my understanding correct, that the number of channels summed over for each pixel is different and is based on '*_chan.fits'?  
2) '*_cube.fits', Moments - Since the gain corrections are applied prior to parameterization, is it safe to infer that the generated cubelets and moment maps have been gain-corrected as well? (as per figure 1) As an extension, does this not change the noise behaviour and ergo also the SNR map? 
3) Flux uncertainty (page 23) - Is the N_pix in equation 15, the sum of '_chan.fits' or the number of pixels in the 2D moment0 map?

**Comment by SoFiA-Admin** [comment]
>     1. '__snr.fits' (page 29) - Is my understanding correct, that the number of channels summed over for each pixel is different and is based on '__chan.fits'?

That is correct. As the moment-0 map is summed over the actual 3D source mask, the number of spectral channels summed over in each pixel will generally be variable.

>     2. '*_cube.fits', Moments - Since the gain corrections are applied prior to parameterization, is it safe to infer that the generated cubelets and moment maps have been gain-corrected as well? (as per figure 1) As an extension, does this not change the noise behaviour and ergo also the SNR map?

If a gain cube is supplied by the user (parameter `input.gain`), then that gain cube will be applied to the data cube prior to parameterisation and output product generation. Hence, all catalogue parameters and data products in the cubelet directory are derived from the gain-corrected cube. While this does change the noise level, it is not expected to significantly affect the SNR calculation, as the latter is derived from the local noise measurement at the location of each source in the gain-corrected data cube. Hence, any changes in the noise level are taken into consideration in the SNR calculation.

>     3. Flux uncertainty (page 23) - Is the N_pix in equation 15, the sum of '_chan.fits' or the number of pixels in the 2D moment0 map?

<var>N</var><sub>pix</sub> in equation 15 is the total number of pixels integrated over and hence everything contained in the 3D source mask. This is equal to the value of the `n_pix` parameter in the source catalogue and should be identical to the sum of all values in the `_chan.fits` map of the source.

**Comment by spectram** [comment]
Awesome. Thanks a lot for the clarification. I wanted to write a thorough sub-section in my thesis on column density calculation and this is super helpful.
