### ISSUE TITLE
SPECSYS3 not copied to cubelets

### ISSUE THREAD

**Issue by kmhess** [SoFiA-Admin/SoFiA-2#97]
In our last meeting I said that I believed SPECSYS3 was copied to the cubelet headers, but that turned out not to be the case.  It would be great if this information could be passed on to any of the data products where SPECSYS would have been passed on.

Tagging @ianjarog who alerted me to this issue.

**Comment by SoFiA-Admin** [comment]
Thanks for checking. I added `SPECSYSn` to the list of things to be copied across for _n_ = 1, 2 and 3 (see 80101de147ec1bc8db74e1729ef0a20b8804ca4b). Please test and let me know if there are any remaining issues.
